set exclude_gates {PadInC PadOut}
load_library ~/Pyxis_SPT_HEP/ic_reflibs/external_libs/GDKgates/GDKgates_utilities/hdl_libs/gdk.syn
read {./SourceCode/FullAdder.vhd ./SourceCode/nBitAdderSubtractor_16Bit.vhd }
set sdf_write_flat_netlist TRUE
optimize
write -format verilog ./Output/nBitAdderSubtractor_16Bit.v
write -format vhdl ./Output/nBitAdderSubtractor_16Bit.vhdl
write -format sdf ./Output/nBitAdderSubtractor_16Bit.sdf
